Repository UWNetworksLab/adn-compiler, pull requests merged in 2024-01, with the labels that each got.

#53 Adding Extensive Comments for Element Compiler
  .gitignore
  README.md
  compiler/README.md
  compiler/docs/semantics.md
  compiler/element/__init__.py
  compiler/element/backend/envoy/finalizer.py
  compiler/element/backend/mrpc/finalizer.py
  compiler/element/deploy.py
  compiler/element/frontend/__init__.py
  compiler/element/frontend/adn.lark
  compiler/element/frontend/parser.py
  compiler/element/frontend/transformer.py
  compiler/element/optimize/merge.py
  compiler/element/props/flow.py
  compiler/element/visitor.py
  compiler/element_compiler_test.py
Labels: documentation

#56 Add State Decorators & Element compiler takes proto/method name as input
  compiler/element/__init__.py
  compiler/element/backend/envoy/finalizer.py
  compiler/element/backend/envoy/templates/build.rs
  compiler/element/backend/envoy/wasmgen.py
  compiler/element/backend/mrpc/finalizer.py
  compiler/element/backend/mrpc/rustgen.py
  compiler/element/frontend/adn.lark
  compiler/element/frontend/printer.py
  compiler/element/frontend/transformer.py
  compiler/element/frontend/util.py
  compiler/element/node.py
  compiler/element_compiler_test.py
  examples/element/statedummy.adn
Labels: enhancement

#60 Add a pass to IR to extract procedure access operations (and a small feature update)
  compiler/element/__init__.py
  compiler/element/backend/analyzer.py
  compiler/element/backend/envoy/boilerplate.py
  compiler/element/backend/envoy/finalizer.py
  compiler/element/backend/envoy/wasmgen.py
  compiler/element/backend/envoy/wasmtype.py
  compiler/element/visitor.py
Labels: optimization, Element Compiler

#87 Element Fixes
  .gitignore
  compiler/element/backend/envoy/wasmgen.py
  compiler/element/backend/envoy/wasmtype.py
  examples/graph/all.yml
  experiments/elements/ping_elements/bandwidthlimit.adn
Labels: bug
